using System.Globalization;
using System.Text;

namespace Hone.SourceControl.PullRequests;

/// <summary>
/// Builds the markdown body for experiment pull requests.
/// Replaces <c>Build-PRBody.ps1</c>.
/// </summary>
public static class PrBodyBuilder
{
    private const string Footer = "---\n*Auto-generated by the Hone agentic optimization harness.*";

    /// <summary>
    /// Builds the full PR body markdown for an experiment.
    /// </summary>
    /// <param name="options">Options describing the experiment outcome and supporting data.</param>
    /// <returns>A markdown string suitable for use as a PR body.</returns>
    public static string Build(PrBodyOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);

        bool isAccepted = string.Equals(options.Outcome, "improved", StringComparison.OrdinalIgnoreCase);

        return isAccepted
            ? BuildAccepted(options)
            : BuildRejected(options);
    }

    private static string BuildAccepted(PrBodyOptions options)
    {
        var sb = new StringBuilder();

        sb.AppendLine(CultureInfo.InvariantCulture, $"## Hone Experiment {options.Experiment}");

        AppendOptional(sb, options.DryRunNotice);
        AppendOptional(sb, options.StackNote);

        sb.AppendLine(CultureInfo.InvariantCulture, $"**Optimization:** {options.Description}");
        sb.AppendLine();

        sb.AppendLine(CultureInfo.InvariantCulture, $"**File changed:** `{options.FilePath}`");

        AppendOptional(sb, options.RcaSummary);
        sb.AppendLine();
        AppendOptional(sb, options.MetricsSummary);
        sb.AppendLine();
        AppendOptional(sb, options.IterationSummary);

        sb.AppendLine(CultureInfo.InvariantCulture, $"**vs baseline improvement:** {FormatImprovement(options.ImprovementPercent)}%");

        AppendOptional(sb, options.ScenarioBreakdown);

        sb.Append(Footer);

        return sb.ToString();
    }

    private static string BuildRejected(PrBodyOptions options)
    {
        var sb = new StringBuilder();

        sb.AppendLine(CultureInfo.InvariantCulture, $"## Hone Experiment {options.Experiment} [REJECTED]");

        AppendOptional(sb, options.DryRunNotice);
        AppendOptional(sb, options.StackNote);

        sb.AppendLine(CultureInfo.InvariantCulture, $"**Optimization attempted:** {options.Description}");
        sb.AppendLine();

        sb.AppendLine(CultureInfo.InvariantCulture, $"**File changed:** `{options.FilePath}`");
        sb.AppendLine();

        sb.AppendLine(CultureInfo.InvariantCulture, $"**Outcome:** {options.OutcomeLabel}");

        AppendOptional(sb, options.OutcomeDetail);
        AppendOptional(sb, options.IterationSummary);
        AppendOptional(sb, options.RcaSummary);
        AppendOptional(sb, options.MetricsSummary);

        sb.AppendLine("> ⚠️ This experiment was rejected. The code change has been reverted.");
        sb.AppendLine("> This PR contains only the experiment artifacts for the record.");
        sb.AppendLine();

        sb.Append(Footer);

        return sb.ToString();
    }

    private static void AppendOptional(StringBuilder sb, string? value)
    {
        if (!string.IsNullOrEmpty(value))
        {
            sb.Append(value);
        }
    }

    private static string FormatImprovement(double? pct)
    {
        return pct.HasValue
            ? pct.Value.ToString("0.##", CultureInfo.InvariantCulture)
            : string.Empty;
    }
}
