<#
.SYNOPSIS
    Builds PR body text for accepted or rejected experiments.

.DESCRIPTION
    Generates the markdown body for experiment pull requests. Supports two
    types: Accepted (improvement detected) and Rejected (regression, stale,
    build failure, test failure, etc.).

    Pre-built sections (metrics tables, RCA, scenario breakdowns) are passed
    as string parameters so this script is a pure template — it does not
    access metrics objects directly.

.PARAMETER Type
    'Accepted' or 'Rejected'.

.PARAMETER Experiment
    Experiment number.

.PARAMETER Description
    Brief description of the optimization attempted.

.PARAMETER FilePath
    The file that was modified.

.PARAMETER StackNote
    Pre-built stack context note (from Build-StackNote).

.PARAMETER DryRunNotice
    Pre-built dry-run notice string.

.PARAMETER MetricsSection
    Pre-built metrics comparison table.

.PARAMETER RcaSection
    Pre-built root cause analysis section.

.PARAMETER OutcomeLabel
    (Rejected only) Emoji + bold label for the rejection reason.

.PARAMETER OutcomeDetail
    (Rejected only) Additional outcome detail text.

.PARAMETER ImprovementPct
    (Accepted only) Overall improvement percentage vs baseline.

.PARAMETER ScenarioBreakdown
    (Accepted only) Pre-built per-scenario breakdown table.

.OUTPUTS
    [string] The PR body markdown.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [ValidateSet('Accepted', 'Rejected')]
    [string]$Type,

    [Parameter(Mandatory)]
    [int]$Experiment,

    [Parameter(Mandatory)]
    [string]$Description,

    [Parameter(Mandatory)]
    [string]$FilePath,

    [string]$StackNote = '',
    [string]$DryRunNotice = '',
    [string]$MetricsSection = '',
    [string]$RcaSection = '',

    # Rejected-specific
    [string]$OutcomeLabel = '',
    [string]$OutcomeDetail = '',

    # Accepted-specific
    [string]$ImprovementPct = '',
    [string]$ScenarioBreakdown = ''
)

if ($Type -eq 'Rejected') {
    return @"
## Hone Experiment $Experiment [REJECTED]
$DryRunNotice$StackNote
**Optimization attempted:** $Description

**File changed:** ``$FilePath``

**Outcome:** $OutcomeLabel
$OutcomeDetail
$RcaSection$MetricsSection
> ⚠️ This experiment was rejected. The code change has been reverted.
> This PR contains only the experiment artifacts for the record.

---
*Auto-generated by the Hone agentic optimization harness.*
"@
} else {
    return @"
## Hone Experiment $Experiment
$DryRunNotice$StackNote
**Optimization:** $Description

**File changed:** ``$FilePath``
$RcaSection
$MetricsSection
**vs baseline improvement:** $ImprovementPct%
$ScenarioBreakdown
---
*Auto-generated by the Hone agentic optimization harness.*
"@
}
