<#
.SYNOPSIS
    Manages the structured optimization queue for the Hone harness.

.DESCRIPTION
    Maintains a JSON queue file (experiment-queue.json) that stores ranked
    optimization opportunities from the analysis agent. The queue drives the
    experiment loop: experiments pick from the queue until it's drained,
    then analysis runs again to replenish it.

    Also regenerates the human-readable experiment-queue.md from the JSON
    source of truth after each mutation.

.PARAMETER Action
    The operation to perform:
    - Init:          Create/replace the queue from analysis output
    - GetNext:       Return the next pending actionable item, mark it in_progress
    - HasActionable: Return $true if pending actionable (non-architecture) items exist
    - MarkDone:      Mark an item as done with an outcome
    - SyncMarkdown:  Regenerate experiment-queue.md from the JSON

.PARAMETER Opportunities
    Array of PSCustomObjects with filePath, explanation, scope (used by Init).

.PARAMETER Experiment
    Current experiment number.

.PARAMETER ItemId
    Queue item ID to update (used by MarkDone).

.PARAMETER Outcome
    Result of the optimization: improved, regressed, stale, skipped (used by MarkDone).

.PARAMETER ConfigPath
    Path to the harness config.psd1 file.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [ValidateSet('Init', 'GetNext', 'HasActionable', 'MarkDone', 'SyncMarkdown')]
    [string]$Action,

    [PSCustomObject[]]$Opportunities,

    [int]$Experiment = 0,

    [int]$ItemId = -1,

    [ValidateSet('improved', 'regressed', 'stale', 'skipped', '')]
    [string]$Outcome,

    [string]$ConfigPath
)

$repoRoot = Split-Path -Parent $PSScriptRoot
Import-Module (Join-Path $PSScriptRoot 'HoneHelpers.psm1') -Force

$config = Get-HoneConfig -ConfigPath $ConfigPath

$metadataDir = Join-Path $repoRoot $config.Api.MetadataPath
if (-not (Test-Path $metadataDir)) {
    New-Item -ItemType Directory -Path $metadataDir -Force | Out-Null
}

$queueJsonPath = Join-Path $metadataDir 'experiment-queue.json'
$queueMdPath = Join-Path $metadataDir 'experiment-queue.md'

# ── Helper: Load queue from JSON ─────────────────────────────────────────────
function Read-Queue {
    if (Test-Path $queueJsonPath) {
        Get-Content $queueJsonPath -Raw | ConvertFrom-Json
    } else {
        [PSCustomObject]@{
            generatedByExperiment = 0
            generatedAt = $null
            items = @()
        }
    }
}

# ── Helper: Save queue to JSON ───────────────────────────────────────────────
function Write-Queue {
    param([PSCustomObject]$Queue)
    $tempPath = "$queueJsonPath.tmp"
    $Queue | ConvertTo-Json -Depth 10 | Out-File -FilePath $tempPath -Encoding utf8
    Move-Item -Path $tempPath -Destination $queueJsonPath -Force
}

# ── Helper: Regenerate markdown from JSON ────────────────────────────────────
function Sync-Markdown {
    param([PSCustomObject]$Queue)

    $lines = @(
        '# Optimization Queue'
        ''
        '> Auto-generated from experiment-queue.json by Hone.'
        '> Do not edit this file directly — it is regenerated after each queue mutation.'
        ''
    )

    if ($Queue.generatedAt) {
        $lines += "**Generated:** experiment $($Queue.generatedByExperiment) at $($Queue.generatedAt)"
        $lines += ''
    }

    foreach ($item in $Queue.items) {
        $check = if ($item.status -eq 'pending' -or $item.status -eq 'in_progress') { ' ' } else { 'x' }
        $scopeTag = if ($item.scope -eq 'architecture') { '[ARCHITECTURE] ' } else { '' }
        $statusNote = switch ($item.status) {
            'in_progress' { ' *(in progress)*' }
            'done' { " *(experiment $($item.triedByExperiment) — $($item.outcome))*" }
            default { '' }
        }
        $lines += "- [$check] **#$($item.id)** ${scopeTag}``$($item.filePath)`` — $($item.title)$statusNote"
    }

    ($lines -join "`n") | Out-File -FilePath $queueMdPath -Encoding utf8
}

# ── Execute the requested action ─────────────────────────────────────────────
switch ($Action) {

    'Init' {
        if (-not $Opportunities -or $Opportunities.Count -eq 0) {
            Write-Verbose 'No opportunities provided for queue initialization.'
            return [PSCustomObject]@{ Success = $false; Count = 0 }
        }

        $items = for ($i = 0; $i -lt $Opportunities.Count; $i++) {
            $opp = $Opportunities[$i]
            $itemTitle = if ($opp.title) { $opp.title } elseif ($opp.explanation) { $opp.explanation } else { '' }

            # Save root-cause document if the analyst provided one
            $rcaPath = $null
            if ($opp.rootCause) {
                $rcaDir = Join-Path $metadataDir 'root-causes'
                if (-not (Test-Path $rcaDir)) {
                    New-Item -ItemType Directory -Path $rcaDir -Force | Out-Null
                }
                $rcaFile = Join-Path $rcaDir "rca-$($i + 1).md"
                $rcaHeader = "# $itemTitle`n`n> **File:** ``$($opp.filePath)`` | **Scope:** $($opp.scope)`n`n"
                ($rcaHeader + $opp.rootCause) | Out-File -FilePath $rcaFile -Encoding utf8
                $rcaPath = $rcaFile
            }

            [PSCustomObject][ordered]@{
                id = $i + 1
                filePath = $opp.filePath
                title = $itemTitle
                explanation = if ($opp.explanation) { $opp.explanation } else { $itemTitle }
                scope = if ($opp.scope) { $opp.scope } else { 'narrow' }
                rootCausePath = $rcaPath
                status = 'pending'
                triedByExperiment = $null
                outcome = $null
            }
        }

        $queue = [PSCustomObject][ordered]@{
            generatedByExperiment = $Experiment
            generatedAt = (Get-Date -Format 'o')
            items = @($items)
        }

        Write-Queue -Queue $queue
        Sync-Markdown -Queue $queue

        & (Join-Path $PSScriptRoot 'Write-HoneLog.ps1') `
            -Phase 'metadata' -Level 'info' `
            -Message "Initialized optimization queue with $($items.Count) items" `
            -Experiment $Experiment `
            -Data @{ count = $items.Count }

        return [PSCustomObject]@{ Success = $true; Count = $items.Count }
    }

    'GetNext' {
        $queue = Read-Queue

        # Find the first pending item that is NOT architecture-scoped
        $next = $queue.items | Where-Object {
            $_.status -eq 'pending' -and $_.scope -ne 'architecture'
        } | Select-Object -First 1

        if (-not $next) {
            return $null
        }

        # Mark as in_progress
        foreach ($item in $queue.items) {
            if ($item.id -eq $next.id) {
                $item.status = 'in_progress'
                break
            }
        }

        Write-Queue -Queue $queue
        Sync-Markdown -Queue $queue

        & (Join-Path $PSScriptRoot 'Write-HoneLog.ps1') `
            -Phase 'metadata' -Level 'info' `
            -Message "Picked queue item #$($next.id): $($next.filePath)" `
            -Experiment $Experiment `
            -Data @{ itemId = $next.id; filePath = $next.filePath }

        return $next
    }

    'HasActionable' {
        $queue = Read-Queue

        $actionable = $queue.items | Where-Object {
            $_.status -eq 'pending' -and $_.scope -ne 'architecture'
        }

        return ($null -ne $actionable -and @($actionable).Count -gt 0)
    }

    'MarkDone' {
        if ($ItemId -lt 0) {
            Write-Warning 'No ItemId provided for MarkDone action.'
            return
        }

        $queue = Read-Queue

        foreach ($item in $queue.items) {
            if ($item.id -eq $ItemId) {
                $item.status = 'done'
                $item.triedByExperiment = $Experiment
                $item.outcome = $Outcome
                break
            }
        }

        Write-Queue -Queue $queue
        Sync-Markdown -Queue $queue

        & (Join-Path $PSScriptRoot 'Write-HoneLog.ps1') `
            -Phase 'metadata' -Level 'info' `
            -Message "Queue item #$ItemId marked done: $Outcome" `
            -Experiment $Experiment `
            -Data @{ itemId = $ItemId; outcome = $Outcome }
    }

    'SyncMarkdown' {
        $queue = Read-Queue
        Sync-Markdown -Queue $queue
    }
}
