<#
.SYNOPSIS
    Maintains an optimization log and opportunity queue across experiments.

.DESCRIPTION
    Manages two markdown files in the metadata directory:
    - optimization-log.md: append-only ledger of tried optimizations and outcomes
    - optimization-queue.md: ranked list of potential optimizations, checked off when tried

.PARAMETER Action
    The operation to perform:
    - AddTried:  Log an optimization that was proposed/applied this experiment
    - AddQueue:  Append new optimization opportunities to the queue
    - MarkTried: Update a queue item as tried, recording the experiment and outcome

.PARAMETER Experiment
    Current experiment number.

.PARAMETER Summary
    Brief description of the optimization (used by AddTried and MarkTried).

.PARAMETER Outcome
    Result of the optimization: 'improved', 'regressed', 'stale' (used by AddTried and MarkTried).

.PARAMETER FilePath
    Target file that was modified (used by AddTried).

.PARAMETER Opportunities
    Array of additional optimization opportunity strings (used by AddQueue).

.PARAMETER ConfigPath
    Path to the harness config.psd1 file.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [ValidateSet('AddTried', 'AddQueue', 'MarkTried')]
    [string]$Action,

    [int]$Experiment = 0,

    [string]$Summary,

    [ValidateSet('improved', 'regressed', 'stale', 'pending', 'queued', '')]
    [string]$Outcome = 'pending',

    [string]$FilePath,

    [string[]]$Opportunities,

    [string[]]$Scopes,

    [string]$ConfigPath
)

$repoRoot = Split-Path -Parent $PSScriptRoot

if (-not $ConfigPath) {
    $ConfigPath = Join-Path $PSScriptRoot 'config.psd1'
}

$config = Import-PowerShellDataFile -Path $ConfigPath

$metadataDir = Join-Path $repoRoot $config.Api.MetadataPath
if (-not (Test-Path $metadataDir)) {
    New-Item -ItemType Directory -Path $metadataDir -Force | Out-Null
}

$logPath   = Join-Path $metadataDir 'optimization-log.md'
$queuePath = Join-Path $metadataDir 'optimization-queue.md'

# ── Ensure files exist with headers ─────────────────────────────────────────
if (-not (Test-Path $logPath)) {
    $logHeader = @"
# Optimization Log

> Auto-generated by Hone. Each entry records an optimization that was proposed and its outcome.

| Experiment | Timestamp | File | Optimization | Outcome |
|-----------|-----------|------|-------------|---------|
"@
    $logHeader | Out-File -FilePath $logPath -Encoding utf8
}

if (-not (Test-Path $queuePath)) {
    $queueHeader = @"
# Optimization Queue

> Auto-generated by Hone. Potential optimizations ranked by expected impact.
> Items are checked off when tried, with a reference to the experiment.

"@
    $queueHeader | Out-File -FilePath $queuePath -Encoding utf8
}

# ── Execute the requested action ────────────────────────────────────────────
switch ($Action) {

    'AddTried' {
        $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm'
        $fileDisplay = if ($FilePath) { "``$FilePath``" } else { '—' }
        $summaryDisplay = if ($Summary) { $Summary } else { '—' }
        $outcomeDisplay = $Outcome

        $entry = "| $Experiment | $timestamp | $fileDisplay | $summaryDisplay | $outcomeDisplay |"
        $entry | Out-File -FilePath $logPath -Append -Encoding utf8

        & (Join-Path $PSScriptRoot 'Write-HoneLog.ps1') `
            -Phase 'metadata' -Level 'info' `
            -Message "Logged optimization: experiment $Experiment — $outcomeDisplay" `
            -Experiment $Experiment `
            -Data @{ summary = $summaryDisplay; outcome = $outcomeDisplay; file = $FilePath }
    }

    'AddQueue' {
        if (-not $Opportunities -or $Opportunities.Count -eq 0) {
            Write-Verbose 'No opportunities to add to the queue.'
            return
        }

        $newEntries = for ($i = 0; $i -lt $Opportunities.Count; $i++) {
            $cleaned = $Opportunities[$i].Trim().TrimStart('-', '*', ' ')
            # Strip any existing scope tags the model may have included in the text
            $cleaned = $cleaned -replace '^\[(NARROW|ARCHITECTURE)\]\s*', ''
            if ($cleaned.Length -gt 0) {
                $scope = if ($Scopes -and $i -lt $Scopes.Count) { $Scopes[$i] } else { $null }
                if ($scope -eq 'architecture') {
                    "- [ ] [ARCHITECTURE] $cleaned"
                } else {
                    "- [ ] $cleaned"
                }
            }
        }

        if ($newEntries.Count -gt 0) {
            # Add a separator noting the source experiment
            $separator = "`n### From Experiment $Experiment`n"
            $separator | Out-File -FilePath $queuePath -Append -Encoding utf8
            ($newEntries -join "`n") | Out-File -FilePath $queuePath -Append -Encoding utf8

            & (Join-Path $PSScriptRoot 'Write-HoneLog.ps1') `
                -Phase 'metadata' -Level 'info' `
                -Message "Added $($newEntries.Count) opportunities to queue from experiment $Experiment" `
                -Experiment $Experiment `
                -Data @{ count = $newEntries.Count }
        }
    }

    'MarkTried' {
        if (-not $Summary -or -not (Test-Path $queuePath)) {
            Write-Verbose 'No summary provided or queue file missing — skipping MarkTried.'
            return
        }

        $content = Get-Content $queuePath -Raw

        # Try to find an unchecked item that matches the summary (fuzzy: first 40 chars)
        $searchKey = if ($Summary.Length -gt 40) { [regex]::Escape($Summary.Substring(0, 40)) } else { [regex]::Escape($Summary) }
        $pattern = "- \[ \] (.*${searchKey}.*)"

        if ($content -match $pattern) {
            $originalLine = $Matches[0]
            $replacement = "- [x] $($Matches[1]) *(experiment $Experiment — $Outcome)*"
            $content = $content.Replace($originalLine, $replacement)
            $content | Out-File -FilePath $queuePath -Encoding utf8

            & (Join-Path $PSScriptRoot 'Write-HoneLog.ps1') `
                -Phase 'metadata' -Level 'info' `
                -Message "Marked queue item as tried: experiment $Experiment" `
                -Experiment $Experiment
        }
        else {
            Write-Verbose "No matching queue item found for: $Summary"
        }
    }
}
