using System.Globalization;
using System.Text;

namespace Hone.Reporting.PullRequest;

/// <summary>
/// Builds PR body markdown for accepted or rejected experiments.
/// Pure template — no I/O, no file system access.
/// Replaces <c>Build-PRBody.ps1</c>.
/// </summary>
internal static class PrBodyBuilder
{
    private const string Footer = "---\n*Auto-generated by the Hone agentic optimization harness.*";

    /// <summary>
    /// Generates the markdown body for an experiment pull request.
    /// </summary>
    /// <param name="options">The PR body options containing all pre-built sections.</param>
    /// <returns>The complete PR body markdown string.</returns>
    public static string Build(PrBodyOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);

        return options.Type == PrBodyType.Rejected
            ? BuildRejected(options)
            : BuildAccepted(options);
    }

    private static string BuildRejected(PrBodyOptions options)
    {
        var sb = new StringBuilder();

        sb.AppendLine(CultureInfo.InvariantCulture, $"## Hone Experiment {options.Experiment} [REJECTED]");

        AppendOptional(sb, options.DryRunNotice);
        AppendOptional(sb, options.StackNote);

        sb.AppendLine(CultureInfo.InvariantCulture, $"**Optimization attempted:** {options.Description}");
        sb.AppendLine();

        sb.AppendLine(CultureInfo.InvariantCulture, $"**File changed:** `{options.FilePath}`");
        sb.AppendLine();

        sb.AppendLine(CultureInfo.InvariantCulture, $"**Outcome:** {options.OutcomeLabel}");

        AppendOptional(sb, options.OutcomeDetail);
        AppendOptional(sb, options.IterationSummary);
        AppendOptional(sb, options.RcaSection);
        AppendOptional(sb, options.MetricsSection);

        sb.AppendLine("> ⚠️ This experiment was rejected. The code change has been reverted.");
        sb.AppendLine("> This PR contains only the experiment artifacts for the record.");
        sb.AppendLine();

        sb.Append(Footer);

        return sb.ToString();
    }

    private static string BuildAccepted(PrBodyOptions options)
    {
        var sb = new StringBuilder();

        sb.AppendLine(CultureInfo.InvariantCulture, $"## Hone Experiment {options.Experiment}");

        AppendOptional(sb, options.DryRunNotice);
        AppendOptional(sb, options.StackNote);

        sb.AppendLine(CultureInfo.InvariantCulture, $"**Optimization:** {options.Description}");
        sb.AppendLine();

        sb.AppendLine(CultureInfo.InvariantCulture, $"**File changed:** `{options.FilePath}`");

        AppendOptional(sb, options.RcaSection);
        sb.AppendLine();
        AppendOptional(sb, options.MetricsSection);
        sb.AppendLine();
        AppendOptional(sb, options.IterationSummary);

        sb.AppendLine(CultureInfo.InvariantCulture, $"**vs baseline improvement:** {options.ImprovementPct}%");

        AppendOptional(sb, options.ScenarioBreakdown);

        sb.Append(Footer);

        return sb.ToString();
    }

    private static void AppendOptional(StringBuilder sb, string? value)
    {
        if (!string.IsNullOrEmpty(value))
        {
            sb.Append(value);
        }
    }
}
