using FluentAssertions;
using Hone.Reporting.PullRequest;
using Hone.TestInfrastructure;
using Xunit;
using Xunit.Abstractions;

namespace Hone.Reporting.Tests.PullRequest;

public sealed class PrBodyBuilderTests(ITestOutputHelper output) : HoneTestBase(output)
{
    private static PrBodyOptions CreateRejectedOptions(
        int experiment = 42,
        string description = "Cache hot-path allocations",
        string filePath = "src/Api/Handlers/OrderHandler.cs",
        string outcomeLabel = "\u274c **Regression detected**",
        string outcomeDetail = "p95 latency increased by 15%.\n") =>
        new()
        {
            Type = PrBodyType.Rejected,
            Experiment = experiment,
            Description = description,
            FilePath = filePath,
            OutcomeLabel = outcomeLabel,
            OutcomeDetail = outcomeDetail,
        };

    private static PrBodyOptions CreateAcceptedOptions(
        int experiment = 7,
        string description = "Pool byte buffers in serializer",
        string filePath = "src/Core/Serializer.cs",
        string improvementPct = "12.3") =>
        new()
        {
            Type = PrBodyType.Accepted,
            Experiment = experiment,
            Description = description,
            FilePath = filePath,
            ImprovementPct = improvementPct,
        };

    // ───── Required tests ─────

    [Fact]
    public void BuildPRBody_ContainsMetrics()
    {
        PrBodyOptions options = CreateAcceptedOptions() with
        {
            MetricsSection = """
                ### Metrics Comparison
                | Metric | Baseline | Experiment |
                |--------|----------|------------|
                | p95    | 120ms    | 98ms       |
                | RPS    | 1500     | 1780       |
                | Errors | 0.1%     | 0.08%      |

                """,
        };

        string body = PrBodyBuilder.Build(options);

        _ = body.Should().Contain("p95");
        _ = body.Should().Contain("RPS");
        _ = body.Should().Contain("Errors");
        _ = body.Should().Contain("120ms");
        _ = body.Should().Contain("1780");
        _ = body.Should().Contain("0.08%");
    }

    [Fact]
    public void BuildPRBody_ContainsStackNote()
    {
        PrBodyOptions options = CreateRejectedOptions() with
        {
            StackNote = "> \U0001f4da This PR is part of a stacked series of experiments.\n",
        };

        string body = PrBodyBuilder.Build(options);

        _ = body.Should().Contain("stacked series");
        _ = body.Should().Contain("\U0001f4da");
    }

    [Fact]
    public void BuildPRBody_ContainsDecision()
    {
        // Rejected — decision and reasoning present
        PrBodyOptions rejected = CreateRejectedOptions(
            outcomeLabel: "\u274c **Regression detected**",
            outcomeDetail: "Error rate increased from 0.1% to 2.3%.\n");
        string rejBody = PrBodyBuilder.Build(rejected);

        _ = rejBody.Should().Contain("[REJECTED]");
        _ = rejBody.Should().Contain("**Outcome:** \u274c **Regression detected**");
        _ = rejBody.Should().Contain("Error rate increased from 0.1% to 2.3%.");
        _ = rejBody.Should().Contain("experiment was rejected");

        // Accepted — no rejection, improvement present
        PrBodyOptions accepted = CreateAcceptedOptions(improvementPct: "15.2");
        string accBody = PrBodyBuilder.Build(accepted);

        _ = accBody.Should().NotContain("[REJECTED]");
        _ = accBody.Should().Contain("**vs baseline improvement:** 15.2%");
    }

    // ───── Structural tests ─────

    [Fact]
    public void Build_RejectedExperiment_MatchesExpectedStructure()
    {
        PrBodyOptions options = CreateRejectedOptions(
            experiment: 42,
            outcomeLabel: "\u26a0\ufe0f **Build failure**",
            outcomeDetail: "CS1002: ; expected\n");

        string body = PrBodyBuilder.Build(options);

        _ = body.Should().StartWith("## Hone Experiment 42 [REJECTED]");
        _ = body.Should().Contain("**Optimization attempted:** Cache hot-path allocations");
        _ = body.Should().Contain("**File changed:** `src/Api/Handlers/OrderHandler.cs`");
        _ = body.Should().Contain("**Outcome:** \u26a0\ufe0f **Build failure**");
        _ = body.Should().Contain("CS1002: ; expected");
        _ = body.Should().Contain("experiment was rejected");
        _ = body.Should().Contain("code change has been reverted");
        _ = body.Should().EndWith("*Auto-generated by the Hone agentic optimization harness.*");
    }

    [Fact]
    public void Build_AcceptedExperiment_MatchesExpectedStructure()
    {
        PrBodyOptions options = CreateAcceptedOptions(experiment: 7);

        string body = PrBodyBuilder.Build(options);

        _ = body.Should().StartWith("## Hone Experiment 7");
        _ = body.Should().NotContain("[REJECTED]");
        _ = body.Should().Contain("**Optimization:** Pool byte buffers in serializer");
        _ = body.Should().Contain("**File changed:** `src/Core/Serializer.cs`");
        _ = body.Should().Contain("**vs baseline improvement:** 12.3%");
        _ = body.Should().EndWith("*Auto-generated by the Hone agentic optimization harness.*");
    }

    [Fact]
    public void Build_DryRunNoticeAppearsBeforeStackNote()
    {
        PrBodyOptions options = CreateRejectedOptions() with
        {
            DryRunNotice = "> \u26a0\ufe0f **DRY RUN** \u2014 no PR will be created.\n",
            StackNote = "> \U0001f4da Stacked experiment series.\n",
        };

        string body = PrBodyBuilder.Build(options);

        int dryRunIndex = body.IndexOf("DRY RUN", StringComparison.Ordinal);
        int stackIndex = body.IndexOf("Stacked", StringComparison.Ordinal);
        _ = dryRunIndex.Should().BeGreaterThanOrEqualTo(0);
        _ = stackIndex.Should().BeGreaterThan(dryRunIndex);
    }

    [Fact]
    public void Build_IterationSummaryIncludedWhenProvided()
    {
        PrBodyOptions options = CreateRejectedOptions() with
        {
            IterationSummary = "### Iteration Summary\n| Attempt | Result |\n| 1 | Build fail |\n| 2 | Pass |\n",
        };

        string body = PrBodyBuilder.Build(options);

        _ = body.Should().Contain("Iteration Summary");
        _ = body.Should().Contain("Build fail");
    }

    [Fact]
    public void Build_AcceptedExperiment_ContainsRcaSection()
    {
        PrBodyOptions options = CreateAcceptedOptions() with
        {
            RcaSection = "\n### Root Cause Analysis\nExcessive allocations in the hot path.\n",
        };

        string body = PrBodyBuilder.Build(options);

        _ = body.Should().Contain("Root Cause Analysis");
        _ = body.Should().Contain("Excessive allocations");
    }

    [Fact]
    public void Build_ThrowsOnNullOptions()
    {
        Action act = () => PrBodyBuilder.Build(null!);

        _ = act.Should().Throw<ArgumentNullException>();
    }

    [Fact]
    public void Build_FooterAlwaysPresent()
    {
        string rejected = PrBodyBuilder.Build(CreateRejectedOptions());
        string accepted = PrBodyBuilder.Build(CreateAcceptedOptions());

        const string Footer = "*Auto-generated by the Hone agentic optimization harness.*";
        _ = rejected.Should().Contain(Footer);
        _ = accepted.Should().Contain(Footer);
    }
}
