using FluentAssertions;
using Hone.SourceControl.PullRequests;
using Xunit;

namespace Hone.SourceControl.Tests.PullRequests;

public sealed class PrBodyBuilderTests
{
    private static PrBodyOptions CreateAcceptedOptions(
        int experiment = 1,
        string description = "optimize loop",
        string filePath = "src/Program.cs",
        double? improvementPercent = 12.5) =>
        new(
            Experiment: experiment,
            Outcome: "improved",
            Description: description,
            FilePath: filePath,
            RcaSummary: null,
            ImprovementPercent: improvementPercent,
            ScenarioBreakdown: null,
            MetricsSummary: null,
            IterationSummary: null,
            StackNote: null,
            DryRunNotice: null,
            OutcomeLabel: null,
            OutcomeDetail: null,
            IsRevert: false);

    private static PrBodyOptions CreateRejectedOptions(
        int experiment = 2,
        string description = "bad refactor",
        string filePath = "src/Service.cs",
        string outcomeLabel = "⛔ **Regressed**",
        string outcomeDetail = "Performance dropped 5%.") =>
        new(
            Experiment: experiment,
            Outcome: "regressed",
            Description: description,
            FilePath: filePath,
            RcaSummary: null,
            ImprovementPercent: null,
            ScenarioBreakdown: null,
            MetricsSummary: null,
            IterationSummary: null,
            StackNote: null,
            DryRunNotice: null,
            OutcomeLabel: outcomeLabel,
            OutcomeDetail: outcomeDetail,
            IsRevert: true);

    // ───── Accepted experiment tests ─────

    [Fact]
    public void Build_AcceptedExperiment_ContainsHeading()
    {
        PrBodyOptions options = CreateAcceptedOptions(experiment: 7);

        string body = PrBodyBuilder.Build(options);

        _ = body.Should().Contain("## Hone Experiment 7");
    }

    [Fact]
    public void Build_AcceptedExperiment_ContainsImprovement()
    {
        PrBodyOptions options = CreateAcceptedOptions(improvementPercent: 15.3);

        string body = PrBodyBuilder.Build(options);

        _ = body.Should().Contain("**vs baseline improvement:** 15.3%");
    }

    [Fact]
    public void Build_AcceptedExperiment_ContainsFilePath()
    {
        PrBodyOptions options = CreateAcceptedOptions(filePath: "src/Engine.cs");

        string body = PrBodyBuilder.Build(options);

        _ = body.Should().Contain("**File changed:** `src/Engine.cs`");
    }

    [Fact]
    public void Build_AcceptedExperiment_ContainsFooter()
    {
        PrBodyOptions options = CreateAcceptedOptions();

        string body = PrBodyBuilder.Build(options);

        _ = body.Should().Contain("Auto-generated by the Hone agentic optimization harness.");
    }

    // ───── Rejected experiment tests ─────

    [Fact]
    public void Build_RejectedExperiment_ContainsRejectedTag()
    {
        PrBodyOptions options = CreateRejectedOptions(experiment: 4);

        string body = PrBodyBuilder.Build(options);

        _ = body.Should().Contain("## Hone Experiment 4 [REJECTED]");
    }

    [Fact]
    public void Build_RejectedExperiment_ContainsOutcomeLabel()
    {
        PrBodyOptions options = CreateRejectedOptions(outcomeLabel: "⛔ **Regressed**");

        string body = PrBodyBuilder.Build(options);

        _ = body.Should().Contain("**Outcome:** ⛔ **Regressed**");
    }

    [Fact]
    public void Build_RejectedExperiment_ContainsRevertNotice()
    {
        PrBodyOptions options = CreateRejectedOptions();

        string body = PrBodyBuilder.Build(options);

        _ = body.Should().Contain("This experiment was rejected. The code change has been reverted.");
    }

    [Fact]
    public void Build_RejectedExperiment_ContainsFooter()
    {
        PrBodyOptions options = CreateRejectedOptions();

        string body = PrBodyBuilder.Build(options);

        _ = body.Should().Contain("Auto-generated by the Hone agentic optimization harness.");
    }
}
